### ISSUE TITLE
Please add license.

### ISSUE THREAD

**Issue by massonpj** [mroth/unindexed#3]
Thanks for posting this, but without an open source license, the default status of your work is "all rights reserved" which means no one can use this ("If you want to conduct your own similar experiment, the source code is here."). Here is a list of Open Source Initiative Approved Licenses: http://opensource.org/licenses.

Thanks - Patrick

**Comment by mroth** [comment]
Hi @massonpj, I had included the license in the `package.json` metadata, which seemed to be the convention for NPM based project, but that's obviously not readily apparent so I will add a standard LICENSE file the to repo itself (I probably should have done this initially, but honestly was never expecting this repo to get that much attention).

While I have you here, may I ask if you have particular license restrictions for your intended usage? (And if so, what your intended usage is?) The project is currently licensed under the [WTFPL](http://www.wtfpl.net/about/), which while being an extremely "free" license, is not currently OSI-approved.

**Comment by massonpj** [comment]
mroth, indeed "license" is a standard property and I should have looked, but I think it is good form to not only name the license but include its language as well--just as you have. Some folks might not be aware of the license's permissions and restrictions. For example, the WTFPL does not explicitly state that there is no warranty: something to consider when your work is purposefully deleting data/content. 

I think your project might get quite a bit of attention, it touches on quite a few current concerns related to privacy, and as you note, ephemerality and persistence on the web (e.g. the right to be forgotten).

My interest is really in fostering experimentation to extend discussions around the issues mentioned above. A permissive license would allow that, and I just wanted to be sure things were all set before sending folks here.

Thanks
