### ISSUE TITLE
Spawn a new copy of itself at another location when indexed

### ISSUE THREAD

**Issue by Marza** [mroth/unindexed#4]
Make the site spawn a new copy of itself at another location when indexed before deleting itself so it can continue to live unindexed at another random location.

**Comment by arthurbarros** [comment]
@Marza  +1

**Comment by salimane** [comment]
+1

**Comment by ArdaIcmez** [comment]
Also +1

**Comment by girishramnani** [comment]
+1

**Comment by mroth** [comment]
That would be an interesting project, but it is not what this particular project was intended to do.  This project is more about embracing ephemerality, not finding ways to persist.

If someone does else want to build that, please open a new issue linking to it, and I will add it to the README so others may find it.
